# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/common.proto\x12\x19nsjail_programming_server\"Q\n\x0eResourceLimits\x12\x12\n\ntime_limit\x18\x03 \x01(\x05\x12\x15\n\rprocess_limit\x18\x04 \x01(\x05\x12\x14\n\x0cmemory_limit\x18\x05 \x01(\x05')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.common_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESOURCELIMITS._serialized_start=49
  _RESOURCELIMITS._serialized_end=130
# @@protoc_insertion_point(module_scope)
