# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/default_settings.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import common_pb2 as proto_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cproto/default_settings.proto\x12\x19nsjail_programming_server\x1a\x12proto/common.proto\"*\n\x13\x43ompilationSettings\x12\x13\n\x0bnsjail_args\x18\x01 \x02(\t\"&\n\x0fRuntimeSettings\x12\x13\n\x0bnsjail_args\x18\x01 \x01(\t\"%\n\x0e\x43ommonSettings\x12\x13\n\x0bnsjail_args\x18\x01 \x01(\t\"\xa8\x02\n\x0fPrivateSettings\x12\x10\n\x08\x62\x61se_dir\x18\x01 \x02(\t\x12\x13\n\x0bnsjail_args\x18\x02 \x02(\t\x12T\n\x1c\x64\x65\x66\x61ult_compilation_settings\x18\x03 \x01(\x0b\x32..nsjail_programming_server.CompilationSettings\x12L\n\x18\x64\x65\x66\x61ult_runtime_settings\x18\x04 \x01(\x0b\x32*.nsjail_programming_server.RuntimeSettings\x12J\n\x17\x64\x65\x66\x61ult_common_settings\x18\x05 \x01(\x0b\x32).nsjail_programming_server.CommonSettings\"\xe6\x02\n\x0ePublicSettings\x12\x13\n\x0bnsjail_path\x18\x01 \x02(\t\x12T\n\x1c\x64\x65\x66\x61ult_compilation_settings\x18\x02 \x01(\x0b\x32..nsjail_programming_server.CompilationSettings\x12L\n\x18\x64\x65\x66\x61ult_runtime_settings\x18\x03 \x01(\x0b\x32*.nsjail_programming_server.RuntimeSettings\x12J\n\x17\x64\x65\x66\x61ult_common_settings\x18\x04 \x01(\x0b\x32).nsjail_programming_server.CommonSettings\x12O\n\x11language_settings\x18\x05 \x03(\x0b\x32\x34.nsjail_programming_server.LanguageDependentSettings\"\x8a\x03\n\x19LanguageDependentSettings\x12\x10\n\x08language\x18\x01 \x02(\t\x12\x10\n\x08\x66ilename\x18\x02 \x02(\t\x12\x17\n\x0f\x62inary_filename\x18\x03 \x01(\t\x12`\n\x13\x63ompilation_options\x18\x04 \x01(\x0b\x32\x43.nsjail_programming_server.LanguageDependentSettings.CommandOptions\x12\\\n\x0fruntime_options\x18\x05 \x02(\x0b\x32\x43.nsjail_programming_server.LanguageDependentSettings.CommandOptions\x1ap\n\x0e\x43ommandOptions\x12\x0c\n\x04path\x18\x01 \x02(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x02(\t\x12\x42\n\x0fresource_limits\x18\x03 \x02(\x0b\x32).nsjail_programming_server.ResourceLimits')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.default_settings_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMPILATIONSETTINGS._serialized_start=79
  _COMPILATIONSETTINGS._serialized_end=121
  _RUNTIMESETTINGS._serialized_start=123
  _RUNTIMESETTINGS._serialized_end=161
  _COMMONSETTINGS._serialized_start=163
  _COMMONSETTINGS._serialized_end=200
  _PRIVATESETTINGS._serialized_start=203
  _PRIVATESETTINGS._serialized_end=499
  _PUBLICSETTINGS._serialized_start=502
  _PUBLICSETTINGS._serialized_end=860
  _LANGUAGEDEPENDENTSETTINGS._serialized_start=863
  _LANGUAGEDEPENDENTSETTINGS._serialized_end=1257
  _LANGUAGEDEPENDENTSETTINGS_COMMANDOPTIONS._serialized_start=1145
  _LANGUAGEDEPENDENTSETTINGS_COMMANDOPTIONS._serialized_end=1257
# @@protoc_insertion_point(module_scope)
