server {
    listen 80;
    # Maximum request size (required for large testcases)
    client_max_body_size 10M;

    location / {
        include proxy_params;
        proxy_pass http://unix:/tmp/nsjail-programming-server.sock;
    }
}
