base_dir: "{{ HOME }}"
nsjail_args: "{{ LANGUAGE_INDEPENDENT_ARGS }} -- {{ LANGUAGE_DEPENDENT_ARGS }}"
default_compilation_settings {
  nsjail_args: "--rw --log {{ LOG_PATH }}"
}
default_runtime_settings {
  nsjail_args: "--rw"
}
default_common_settings {
  nsjail_args: "-e --cwd / -c {{ ROOT_DIRECTORY }} --time_limit {{ TIME_LIMIT }} --rlimit_as {{ MEMORY_LIMIT }} --rlimit_nproc {{ PROCESS_LIMIT }} --env TMP=/ --env TMPDIR=/ --rlimit_fsize 100 --rlimit_nofile 1000"
}
